config/routes.rb
Rails.application.routes.draw do

devise_for :admins, controllers: {
  sessions:      'admins/sessions',
  passwords:     'admins/passwords',
  registrations: 'admins/registrations'
}

devise_for :end_users, controllers: {
  sessions:      'end_users/sessions',
  passwords:     'end_users/passwords',
  registrations: 'end_users/registrations'
}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'homes#top'
  get 'home/about' => 'homes#about'
  
  resources :searchs,only: [:index]

#ユーザー側  
  namespace :public do
    resources :items,only: [:index,:show,:edit,:new,:create,:update,:destroy] do
        resources :comments, only: [:create, :destroy]
        resource :favorites, only: [:create, :destroy]
    end
    resources :end_users,only: [:index,:show,:edit,:update,:create] do
      get 'follow'
      get 'follower'
      resource :relationships, only: [:create, :destroy]
      get 'followings' => 'relationships#followings', as: 'followings'
      get 'followers' => 'relationships#followers', as: 'followers'
    end
    resources :orders,only: [:index,:create,:show,:new] do
     collection do
      get 'buyer'
      get 'thanks'
      post 'check'
     end
    end
    resources :shipping_addresses,only: [:index,:destroy,:update,:edit,:create]
    resources :cart_items,only: [:index,:destroy,:update,:create] do
     collection do
      delete 'destroy_all'
     end
   end
  end
  
  
  
# 管理側
  namespace :admin do
    resources :genres,only: [:index,:edit,:update,:create]
    resources :end_users,only: [:index,:show]
    resources :items,only: [:index,:edit,:show]
    resources :orders,only: [:index,:show,:update]
    resources :adimin,only: [:index,:create,:destroy]
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
    belongs_to :end_user
    belongs_to :item
    validates :number,presence: true
    
    def add_tax_price_total
        self.number * self.item.add_tax_price
    end
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :end_user
    belongs_to :item
    validates :comment, presence: true
end

app/models/end_user.rb
class EndUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  
  has_many :shipping_addresses, dependent: :destroy
  has_many :cart_items,dependent: :destroy
  has_many :orders,dependent: :destroy
  has_many :items, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  
  # 自分がフォローされる（被フォロー）側の関係性
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  # 自分がフォローする（与フォロー）側の関係性
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  # 被フォロー関係を通じて参照→自分をフォローしている人
  has_many :followers, through: :reverse_of_relationships, source: :follower
  # 与フォロー関係を通じて参照→自分がフォローしている人
  has_many :followings, through: :relationships, source: :followed
  
  
  attachment :profile_image
  
  
  
  def follow(end_user_id)
    relationships.create(followed_id: end_user_id)
  end

  def unfollow(end_user_id)
    relationships.find_by(followed_id: end_user_id).destroy
  end

  def following?(end_user)
    followings.include?(end_user)
  end
  
  def total_price
    total = 0
    self.cart_items.each do |cart_item|
      total += cart_item.add_tax_price_total
    end
    total
  end
  
  
  def self.search(search,text)
    if search 
      @user = EndUser.where("nick_name like ?","%#{text}%")
    else
      @user = EndUser.none
    end
  end
  
end

  

app/models/favorite.rb
class Favorite < ApplicationRecord
    belongs_to :end_user
    belongs_to :item
end

app/models/genre.rb
class Genre < ApplicationRecord
    has_many :items
    has_many :cart_items,dependent: :destroy
    has_many :order_items
end

app/models/item.rb
class Item < ApplicationRecord
    has_many :cart_items,dependent: :destroy
    has_many :order_items
    has_many :comments, dependent: :destroy
    has_many :favorites, dependent: :destroy
    has_many :items
    belongs_to :end_user

    belongs_to :genre


    
    attachment :image
    
    def favorited_by?(user)
        favorites.where(end_user_id: user.id).exists?
    end
    
    def add_tax_price
        (self.non_price * 1.10).round
    end
    
    def self.search(search,text)
        if search
            @item = Item.where("name like ?","%#{text}%")
        else
            @item = Item.none
        end
    end

end

app/models/order.rb
class Order < ApplicationRecord
    has_many :order_items
    belongs_to :end_user
    belongs_to :item
    
    
    enum payment_method: {"クレジット":0,"銀行":1}
    
    def total_price #商品合計をメソッドで計算
        total = 0
        self.order_items.each do |order_item|
            total += order_item.tax_included_price*order_item.number
    end
        total
    end


    def total_order #商品個数をメソッドで計算
        self.order_items.count
    end
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
    belongs_to :item
    belongs_to :order
end

app/models/relationship.rb
class Relationship < ApplicationRecord
    #follower_idカラムの値から、end_usersテーブルのレコードを参照できるように
    belongs_to :follower, class_name: "EndUser"
    belongs_to :followed, class_name: "EndUser"
end

app/models/shipping_address.rb
class ShippingAddress < ApplicationRecord
    belongs_to :end_user
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/searchs_helper.rb
module SearchsHelper
end

app/views/admins/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>

app/views/layouts/_header.html.erb
<!DOCTYPE html>
<html>
    <header>
      　<div class="logo">
          <%= link_to root_path do %>
          <%= image_tag "logo.png" %>
    　  　  <% end %>
　　    </div>
　　    <div class="navbar_list">
            <ul class="navbar">
                <% if end_user_signed_in? %>
                  <li>
                    <%= current_end_user.nick_name %>さんでログイン中！！
                  </li>
                  <li> 
                    <%= link_to 'マイページ',public_end_user_path(current_end_user) %>
                  </li>
                  <li>
                    <%= link_to 'ユーザーの一覧',public_end_users_path %>
                  </li>
                  <li> 
                    <%= link_to '商品一覧',public_items_path %>
                  </li>
                  <li> 
                    <%= link_to 'カート',public_cart_items_path %>
                  </li>
                  <li> 
                    <%= link_to 'ログアウト', destroy_end_user_session_path, method: :delete %>
                  </li>
                  <li>
                    <%= form_with url: searchs_path, method: :get, local: true do |f| %>
                      <%= f.text_field :text  %>
                      <%= f.select :faculty, [["ユーザー", "EndUser"],["商品", "Item"]] %>
                      <%= f.hidden_field :search %>
                      <%= f.submit "検索" %>
                    <% end %>
                  </li>
                <% elsif admin_signed_in? %>
                  <li> 
                    <%= link_to '商品⼀覧 ',admin_items_path %>
                  </li>
                  <li>
                    <%= link_to '注文履歴一覧 ',admin_orders_path %>
                  </li>
                  <li> 
                    <%= link_to '会員⼀覧 ', admin_end_users_path %>
                  </li>
                  <li> 
                    <%= link_to 'ジャンル⼀覧 ',admin_genres_path %>
                  </li>
                  <li> 
                    <%= link_to 'ログアウト', destroy_admin_session_path, method: :delete %>
                  </li>
                <% else %>
                <!--ログインしてないとき-->
                  <li>
                    <%= link_to '概要', home_about_path %>
                  </li>
                  <li> 
                    <%= link_to '商品一覧', public_items_path %>
                  </li>
                  <li> 
                    <%= link_to '新規登録', new_end_user_registration_path %>
                  </li>
                  <li> 
                    <%= link_to 'ログイン', new_end_user_session_path %>
                  </li>
                  <li>
                    <%= link_to '管理者ログイン',new_admin_session_path %>
                  </li>
                <% end %>
        　   </ul>
        　</div>
        </div>
    　</nav>
    </header>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>facty</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <p class='notice'><%= notice %></p>
    <p class='notice'><%= alert %></p>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>