config/routes.rb
Rails.application.routes.draw do

devise_for :admins, controllers: {
  sessions:      'admins/sessions',
  passwords:     'admins/passwords',
  registrations: 'admins/registrations'
}

devise_for :end_users, controllers: {
  sessions:      'end_users/sessions',
  passwords:     'end_users/passwords',
  registrations: 'end_users/registrations'
}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'homes#top'
  get 'home/about' => 'homes#about'
  
  resources :searchs,only: [:index]

#ユーザー側  
  namespace :public do
    resources :items,only: [:index,:show,:edit,:new,:create,:update,:destroy] do
        resources :comments, only: [:create, :destroy]
        resource :favorites, only: [:create, :destroy]
    end
    resources :end_users,only: [:index,:show,:edit,:update,:create] do
      get 'follow'
      get 'follower'
      resource :relationships, only: [:create, :destroy]
      get 'followings' => 'relationships#followings', as: 'followings'
      get 'followers' => 'relationships#followers', as: 'followers'
    end
    resources :orders,only: [:index,:create,:show,:new] do
     collection do
      get 'buyer'
      get 'thanks'
      post 'check'
     end
    end
    resources :shipping_addresses,only: [:index,:destroy,:update,:edit,:create]
    resources :cart_items,only: [:index,:destroy,:update,:create] do
     collection do
      delete 'destroy_all'
     end
   end
  end
  
  
  
# 管理側
  namespace :admin do
    resources :genres,only: [:index,:edit,:update,:create]
    resources :end_users,only: [:index,:show]
    resources :items,only: [:index,:edit,:show]
    resources :orders,only: [:index,:show,:update]
    resources :adimin,only: [:index,:create,:destroy]
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
    belongs_to :end_user
    belongs_to :item
    validates :number,presence: true
    
    def add_tax_price_total
        self.number * self.item.add_tax_price
    end
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :end_user
    belongs_to :item
    validates :comment, presence: true
end

app/models/end_user.rb
class EndUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  
  has_many :shipping_addresses, dependent: :destroy
  has_many :cart_items,dependent: :destroy
  has_many :orders,dependent: :destroy
  has_many :items, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  
  # 自分がフォローされる（被フォロー）側の関係性
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  # 自分がフォローする（与フォロー）側の関係性
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  # 被フォロー関係を通じて参照→自分をフォローしている人
  has_many :followers, through: :reverse_of_relationships, source: :follower
  # 与フォロー関係を通じて参照→自分がフォローしている人
  has_many :followings, through: :relationships, source: :followed
  
  
  attachment :profile_image
  
  
  
  def follow(end_user_id)
    relationships.create(followed_id: end_user_id)
  end

  def unfollow(end_user_id)
    relationships.find_by(followed_id: end_user_id).destroy
  end

  def following?(end_user)
    followings.include?(end_user)
  end
  
  def total_price
    total = 0
    self.cart_items.each do |cart_item|
      total += cart_item.add_tax_price_total
    end
    total
  end
  
  
  def self.search(search,text)
    if search 
      @user = EndUser.where("nick_name like ?","%#{text}%")
    else
      @user = EndUser.none
    end
  end
  
end

  

app/models/favorite.rb
class Favorite < ApplicationRecord
    belongs_to :end_user
    belongs_to :item
end

app/models/genre.rb
class Genre < ApplicationRecord
    has_many :items
    has_many :cart_items,dependent: :destroy
    has_many :order_items
end

app/models/item.rb
class Item < ApplicationRecord
    has_many :cart_items,dependent: :destroy
    has_many :order_items
    has_many :comments, dependent: :destroy
    has_many :favorites, dependent: :destroy
    has_many :items
    belongs_to :end_user

    belongs_to :genre


    
    attachment :image
    
    def favorited_by?(user)
        favorites.where(end_user_id: user.id).exists?
    end
    
    def add_tax_price
        (self.non_price * 1.10).round
    end
    
    def self.search(search,text)
        if search
            @item = Item.where("name like ?","%#{text}%")
        else
            @item = Item.none
        end
    end

end

app/models/order.rb
class Order < ApplicationRecord
    has_many :order_items
    belongs_to :end_user
    belongs_to :item
    
    
    enum payment_method: {"クレジット":0,"銀行":1}
    
    def total_price #商品合計をメソッドで計算
        total = 0
        self.order_items.each do |order_item|
            total += order_item.tax_included_price*order_item.number
    end
        total
    end


    def total_order #商品個数をメソッドで計算
        self.order_items.count
    end
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
    belongs_to :item
    belongs_to :order
end

app/models/relationship.rb
class Relationship < ApplicationRecord
    #follower_idカラムの値から、end_usersテーブルのレコードを参照できるように
    belongs_to :follower, class_name: "EndUser"
    belongs_to :followed, class_name: "EndUser"
end

app/models/shipping_address.rb
class ShippingAddress < ApplicationRecord
    belongs_to :end_user
end

app/controllers/searchs_controller.rb
class SearchsController < ApplicationController
    def index
      @faculty = params[:faculty]
      @search = params[:search]
      @text = params[:text]
      if @faculty == 'EndUser'
        @users = EndUser.search(params[:search],params[:text])
      else
        @items = Item.search(params[:search],params[:text])
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/searchs_helper.rb
module SearchsHelper
end

app/views/searchs/_favorites.html.erb
<% if end_user_signed_in? %>
    <% if item.favorited_by?(current_end_user) %>
        <p>
            <%= link_to public_item_favorites_path(item),remote: true, method: :delete do %>
            ♥<%= item.favorites.count %>
            <% end %>
        </p>
    <% else %>
        <p>
            <%= link_to public_item_favorites_path(item),remote: true, method: :post do %>
            ♡<%= item.favorites.count %>
            <% end %>
        </p>
    <% end %>
<% else %>
    <p> ♥<%= item.favorites.count %></p>
<% end %>

app/views/searchs/index.html.erb
<% if @faculty == 'EndUser' %>
    <h1 class='search'>
        [<%= @text %>]の検索結果
    </h1>
<% else %>
    <h1 class='search'>
        [<%= @text %>]の検索結果
    </h1>
<% end %>
<% if @faculty == 'EndUser' %>
    <div class="col-md-8 offset-md-1">
        <table class="table">
            <tr>
                <th>プロフィール画像</th>
                <th>ニックネーム</th>
                <th>自己紹介</th>
                <th colspan="3"></th>
            </tr>
            <% @users.each do |user| %>
            <tr>
                <td>
                    <%= attachment_image_tag user, :profile_image,  format: 'jpeg', size: "40x40", fallback: "no_image.jpg", class: "rounded-circle" %>
                </td>
                <td>
                    <%= user.nick_name %>
                </td>
                <td>
                    <%= user.introduction %>
                </td>
                <td>
                    <%= link_to "詳細を見る",public_end_user_path(user) %>
                </td>
            </tr>
            <% end %>
        </table>
    </div>
<% else %>
    <% @items.each do |item| %>
    <div class='item_index'>
        <div>
            <%= link_to public_item_path(item.id) do %>
            <%= attachment_image_tag item, :image, format: 'jpeg',size: "700x600", fallback: "no_image.jpg"%>
        </div>
        <div class='item_index_profil'>
            <%= attachment_image_tag item.end_user, :profile_image, format: 'jpeg',size: "80x80", fallback: "no_image.jpg", class: "rounded-circle" %> <%= item.end_user.nick_name %>
        </div>
        <p>
            商品名：<%= item.name %>
        </p>
        <p>
            <%= item.contents %>
        </p>
        <p>
            ジャンル：<%= item.genre.name %>
        </p>
        <p>
            ¥<%= item.non_price.to_s(:delimited) %>
        </p>
        <p>
            <%= item.created_at.strftime('%Y/%m/%d') %>
        </p>
        <% end %>
        <div class="item_<%= item.id %>">
            <%= render 'favorites', item: item %>
        </div>
    </div>
    <% end %>
<% end %>